"""Add schedule

Revision ID: 0fc3573c081d
Revises: 3eff3ffbfe87
Create Date: 2020-04-12 14:24:46.552665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc3573c081d'
down_revision = '3eff3ffbfe87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('finish_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['activity'], ['sport_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_schedule')
    # ### end Alembic commands ###
