"""Add the limit of students

Revision ID: 719fe46a0b15
Revises: da9012c31020
Create Date: 2020-05-03 11:36:45.533795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719fe46a0b15'
down_revision = 'da9012c31020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_activities', sa.Column('max_students', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_activities', 'max_students')
    # ### end Alembic commands ###
