"""Add relationship schedule relationship for sport activity

Revision ID: 774323c7a621
Revises: 0fc3573c081d
Create Date: 2020-04-12 16:44:56.256542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774323c7a621'
down_revision = '0fc3573c081d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_schedule_activity_fkey', 'activity_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'activity_schedule', 'sport_activities', ['activity'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_schedule', type_='foreignkey')
    op.create_foreign_key('activity_schedule_activity_fkey', 'activity_schedule', 'sport_activities', ['activity'], ['id'])
    # ### end Alembic commands ###
