"""Fix table names

Revision ID: 89d206f46d82
Revises: 6d3e8beffd37
Create Date: 2020-03-15 12:57:07.248746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d206f46d82'
down_revision = '6d3e8beffd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_assignments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'activity_id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sport_activities.id'], ),
    sa.ForeignKeyConstraint(['leader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_hours_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('hours_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.String(length=32)), nullable=False))
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'roles')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    op.drop_table('sport_hours_records')
    op.drop_table('clubs')
    op.drop_table('activity_assignments')
    op.drop_table('sport_activities')
    # ### end Alembic commands ###
