"""Add a unique constraint on the sport hours records

Revision ID: 98dbd94c1198
Revises: 89d206f46d82
Create Date: 2020-03-15 13:19:53.449729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dbd94c1198'
down_revision = '89d206f46d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_hours_records', 'hours_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'sport_hours_records', ['student_id', 'activity_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sport_hours_records', type_='unique')
    op.alter_column('sport_hours_records', 'hours_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
