"""make user email primary key

Revision ID: c862ba1d29ef
Revises: 
Create Date: 2020-04-05 19:01:24.346386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c862ba1d29ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_assignment',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'student_id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sport_activities.id'], ),
    sa.ForeignKeyConstraint(['leader'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_hours_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('hours_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'activity_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_hours_records')
    op.drop_table('clubs')
    op.drop_table('activity_assignment')
    op.drop_table('users')
    op.drop_table('sport_activities')
    # ### end Alembic commands ###
