"""Change activity assignment into a table

Revision ID: f2a78ec75aa9
Revises: 98dbd94c1198
Create Date: 2020-03-15 14:37:29.160536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a78ec75aa9'
down_revision = '98dbd94c1198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_assignment',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'student_id')
    )
    op.drop_table('activity_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_assignments',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['sport_activities.id'], name='activity_assignments_activity_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='activity_assignments_student_id_fkey'),
    sa.PrimaryKeyConstraint('student_id', 'activity_id', name='activity_assignments_pkey')
    )
    op.drop_table('activity_assignment')
    # ### end Alembic commands ###
