DROP TABLE Users CASCADE;

DROP TABLE Instructors CASCADE;

DROP TABLE SportActivities CASCADE;

DROP TABLE Clubs CASCADE;

DROP TABLE ClubLeaders CASCADE;

DROP TABLE Admins CASCADE;

DROP TABLE Students CASCADE;

DROP TABLE Hours CASCADE;

DROP TABLE ClubParticipants CASCADE;

DROP TABLE PrimarySportActivities CASCADE;